CREATE TABLE defillama_enriched_pools (
  pool VARCHAR(255) PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL,
  project VARCHAR(255) NOT NULL,
  chain VARCHAR(255) NOT NULL,
  symbol VARCHAR(255) NOT NULL,
  pool_meta TEXT,
  underlying_tokens TEXT [],
  reward_tokens TEXT [],
  tvl_usd NUMERIC,
  apy NUMERIC,
  apy_base NUMERIC,
  apy_reward NUMERIC,
  il_7d NUMERIC,
  apy_base_7d NUMERIC,
  volume_usd_1d NUMERIC,
  volume_usd_7d NUMERIC,
  apy_base_inception NUMERIC,
  url TEXT,
  apy_pct_1d NUMERIC,
  apy_pct_7d NUMERIC,
  apy_pct_30d NUMERIC,
  apy_mean_30d NUMERIC,
  stablecoin BOOLEAN,
  il_risk VARCHAR(50),
  exposure VARCHAR(50),
  return_value NUMERIC,
  count INTEGER,
  apy_mean_expanding NUMERIC,
  apy_std_expanding NUMERIC,
  mu NUMERIC,
  sigma NUMERIC,
  outlier BOOLEAN,
  project_factorized INTEGER,
  chain_factorized INTEGER,
  predicted_class VARCHAR(50),
  predicted_probability NUMERIC,
  binned_confidence NUMERIC,
  pool_old VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
